FROM golang:1.17

RUN apt update

RUN curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.83/pact-1.88.83-linux-x86_64.tar.gz
RUN tar xzf pact-1.88.83-linux-x86_64.tar.gz
RUN mv pact /usr/local/ && chmod +x /usr/local/pact/bin
RUN chmod +x /usr/local/pact/bin
ENV PATH="/usr/local/pact/bin:/pact/bin:$PATH"

#RUN mkdir /app
#COPY . /app
#WORKDIR /app

#RUN go mod tidy -go=1.16 && go mod tidy -go=1.17



