variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - test
  - package
build:
  stage: build
  image: golang:1.17.0-alpine3.14
  before_script:
    - go mod tidy -go=1.16 && go mod tidy -go=1.17
  script:
    - go build -o bin/main main.go

test:
  stage: test
  image: golang:1.17
  variables:
    CI : $CI
  before_script:
    - go mod tidy -go=1.16 && go mod tidy -go=1.17
  script:
    - go test ./todo/tests ./postgre/ ./server/ -v

package:
  stage: package
  image: docker:18-git
  services:
    - name: docker:18-dind
  variables:
    DOCKER_REGISTRY_NAME: $MY_CI_REGISTRY_NAME:$CI_PIPELINE_ID
  script:
    - docker login -u $MY_CI_DOCKER_USER --password $MY_CI_DOCKER_PASS
    - docker build -t $DOCKER_REGISTRY_NAME $CI_PROJECT_DIR
    - docker push $DOCKER_REGISTRY_NAME
